// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/Enum/AxeQuality.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lumber.Enum {

  /// <summary>Holder for reflection information generated from proto/Enum/AxeQuality.proto</summary>
  public static partial class AxeQualityReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/Enum/AxeQuality.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AxeQualityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtwcm90by9FbnVtL0F4ZVF1YWxpdHkucHJvdG8SC2x1bWJlci5FbnVtKi8K",
            "C0VBeGVRdWFsaXR5EggKBElyb24QABIKCgZTaWx2ZXIQARIKCgZHb2xkZW4Q",
            "AmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lumber.Enum.EAxeQuality), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 斧子品质
  /// </summary>
  public enum EAxeQuality {
    /// <summary>
    /// 铁斧子
    /// </summary>
    [pbr::OriginalName("Iron")] Iron = 0,
    /// <summary>
    /// 银斧子
    /// </summary>
    [pbr::OriginalName("Silver")] Silver = 1,
    /// <summary>
    /// 金斧子
    /// </summary>
    [pbr::OriginalName("Golden")] Golden = 2,
  }

  #endregion

}

#endregion Designer generated code
