// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/Message/DoLumber.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lumber.Message {

  /// <summary>Holder for reflection information generated from proto/Message/DoLumber.proto</summary>
  public static partial class DoLumberReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/Message/DoLumber.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DoLumberReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chxwcm90by9NZXNzYWdlL0RvTHVtYmVyLnByb3RvEg5sdW1iZXIuTWVzc2Fn",
            "ZRobcHJvdG8vRW51bS9BeGVRdWFsaXR5LnByb3RvIjwKD0RvTHVtYmVyUmVx",
            "dWVzdBIpCgdxdWFsaXR5GAEgASgOMhgubHVtYmVyLkVudW0uRUF4ZVF1YWxp",
            "dHkidQoQRG9MdW1iZXJSZXNwb25zZRItCgZzdGF0dXMYASABKA4yHS5sdW1i",
            "ZXIuTWVzc2FnZS5FTHVtYmVyU3RhdHVzEhAKCHJvc2VDb3N0GAIgASgNEhAK",
            "CGNvaW5HYWluGAMgASgNEg4KBnByb3BJZBgEIAEoDSpfCg1FTHVtYmVyU3Rh",
            "dHVzEgsKB1N1Y2Nlc3MQABIWChJUcmVlTGV2ZWxOb3RFbm91Z2gQARIVChFB",
            "eGVMZXZlbE5vdEVub3VnaBACEhIKDk5vUmV3YXJkSW5Mb290EANiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Lumber.Enum.AxeQualityReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lumber.Message.ELumberStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lumber.Message.DoLumberRequest), global::Lumber.Message.DoLumberRequest.Parser, new[]{ "Quality" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lumber.Message.DoLumberResponse), global::Lumber.Message.DoLumberResponse.Parser, new[]{ "Status", "RoseCost", "CoinGain", "PropId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 砍树返回状态
  /// </summary>
  public enum ELumberStatus {
    /// <summary>
    ///成功掉落午评
    /// </summary>
    [pbr::OriginalName("Success")] Success = 0,
    /// <summary>
    /// 仙果砍飞了(树等级太低)
    /// </summary>
    [pbr::OriginalName("TreeLevelNotEnough")] TreeLevelNotEnough = 1,
    /// <summary>
    ///斧头断了(斧头等级太低)
    /// </summary>
    [pbr::OriginalName("AxeLevelNotEnough")] AxeLevelNotEnough = 2,
    /// <summary>
    ///奖池中奖励不够
    /// </summary>
    [pbr::OriginalName("NoRewardInLoot")] NoRewardInLoot = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 砍树
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DoLumberRequest : pb::IMessage<DoLumberRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DoLumberRequest> _parser = new pb::MessageParser<DoLumberRequest>(() => new DoLumberRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DoLumberRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lumber.Message.DoLumberReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DoLumberRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DoLumberRequest(DoLumberRequest other) : this() {
      quality_ = other.quality_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DoLumberRequest Clone() {
      return new DoLumberRequest(this);
    }

    /// <summary>Field number for the "quality" field.</summary>
    public const int QualityFieldNumber = 1;
    private global::Lumber.Enum.EAxeQuality quality_ = global::Lumber.Enum.EAxeQuality.Iron;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lumber.Enum.EAxeQuality Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DoLumberRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DoLumberRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Quality != other.Quality) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Quality != global::Lumber.Enum.EAxeQuality.Iron) hash ^= Quality.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Quality != global::Lumber.Enum.EAxeQuality.Iron) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Quality);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Quality != global::Lumber.Enum.EAxeQuality.Iron) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Quality);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Quality != global::Lumber.Enum.EAxeQuality.Iron) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Quality);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DoLumberRequest other) {
      if (other == null) {
        return;
      }
      if (other.Quality != global::Lumber.Enum.EAxeQuality.Iron) {
        Quality = other.Quality;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Quality = (global::Lumber.Enum.EAxeQuality) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Quality = (global::Lumber.Enum.EAxeQuality) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DoLumberResponse : pb::IMessage<DoLumberResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DoLumberResponse> _parser = new pb::MessageParser<DoLumberResponse>(() => new DoLumberResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DoLumberResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lumber.Message.DoLumberReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DoLumberResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DoLumberResponse(DoLumberResponse other) : this() {
      status_ = other.status_;
      roseCost_ = other.roseCost_;
      coinGain_ = other.coinGain_;
      propId_ = other.propId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DoLumberResponse Clone() {
      return new DoLumberResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Lumber.Message.ELumberStatus status_ = global::Lumber.Message.ELumberStatus.Success;
    /// <summary>
    ///砍树返回状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lumber.Message.ELumberStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "roseCost" field.</summary>
    public const int RoseCostFieldNumber = 2;
    private uint roseCost_;
    /// <summary>
    ///消耗的玫瑰数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RoseCost {
      get { return roseCost_; }
      set {
        roseCost_ = value;
      }
    }

    /// <summary>Field number for the "coinGain" field.</summary>
    public const int CoinGainFieldNumber = 3;
    private uint coinGain_;
    /// <summary>
    ///获得金币数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CoinGain {
      get { return coinGain_; }
      set {
        coinGain_ = value;
      }
    }

    /// <summary>Field number for the "propId" field.</summary>
    public const int PropIdFieldNumber = 4;
    private uint propId_;
    /// <summary>
    ///掉落物品id, 0表示未掉落
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PropId {
      get { return propId_; }
      set {
        propId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DoLumberResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DoLumberResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (RoseCost != other.RoseCost) return false;
      if (CoinGain != other.CoinGain) return false;
      if (PropId != other.PropId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Lumber.Message.ELumberStatus.Success) hash ^= Status.GetHashCode();
      if (RoseCost != 0) hash ^= RoseCost.GetHashCode();
      if (CoinGain != 0) hash ^= CoinGain.GetHashCode();
      if (PropId != 0) hash ^= PropId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Lumber.Message.ELumberStatus.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (RoseCost != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(RoseCost);
      }
      if (CoinGain != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(CoinGain);
      }
      if (PropId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PropId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Lumber.Message.ELumberStatus.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (RoseCost != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(RoseCost);
      }
      if (CoinGain != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(CoinGain);
      }
      if (PropId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PropId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Lumber.Message.ELumberStatus.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (RoseCost != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RoseCost);
      }
      if (CoinGain != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CoinGain);
      }
      if (PropId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PropId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DoLumberResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Lumber.Message.ELumberStatus.Success) {
        Status = other.Status;
      }
      if (other.RoseCost != 0) {
        RoseCost = other.RoseCost;
      }
      if (other.CoinGain != 0) {
        CoinGain = other.CoinGain;
      }
      if (other.PropId != 0) {
        PropId = other.PropId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Lumber.Message.ELumberStatus) input.ReadEnum();
            break;
          }
          case 16: {
            RoseCost = input.ReadUInt32();
            break;
          }
          case 24: {
            CoinGain = input.ReadUInt32();
            break;
          }
          case 32: {
            PropId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Lumber.Message.ELumberStatus) input.ReadEnum();
            break;
          }
          case 16: {
            RoseCost = input.ReadUInt32();
            break;
          }
          case 24: {
            CoinGain = input.ReadUInt32();
            break;
          }
          case 32: {
            PropId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
