// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/Spec/Fruit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lumber.Spec {

  /// <summary>Holder for reflection information generated from proto/Spec/Fruit.proto</summary>
  public static partial class FruitReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/Spec/Fruit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FruitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZwcm90by9TcGVjL0ZydWl0LnByb3RvEgtsdW1iZXIuU3BlYyI9CgVGcnVp",
            "dBIPCgdQb29sX0lEGAEgASgFEg8KB1Byb3BfSUQYAiABKAUSEgoKUHJvcF9S",
            "YW5nZRgDIAMoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lumber.Spec.Fruit), global::Lumber.Spec.Fruit.Parser, new[]{ "PoolID", "PropID", "PropRange" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Fruit : pb::IMessage<Fruit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Fruit> _parser = new pb::MessageParser<Fruit>(() => new Fruit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Fruit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lumber.Spec.FruitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Fruit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Fruit(Fruit other) : this() {
      poolID_ = other.poolID_;
      propID_ = other.propID_;
      propRange_ = other.propRange_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Fruit Clone() {
      return new Fruit(this);
    }

    /// <summary>Field number for the "Pool_ID" field.</summary>
    public const int PoolIDFieldNumber = 1;
    private int poolID_;
    /// <summary>
    /// 仙果ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PoolID {
      get { return poolID_; }
      set {
        poolID_ = value;
      }
    }

    /// <summary>Field number for the "Prop_ID" field.</summary>
    public const int PropIDFieldNumber = 2;
    private int propID_;
    /// <summary>
    /// 包含道具ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PropID {
      get { return propID_; }
      set {
        propID_ = value;
      }
    }

    /// <summary>Field number for the "Prop_Range" field.</summary>
    public const int PropRangeFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_propRange_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> propRange_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 道具数量区间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> PropRange {
      get { return propRange_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Fruit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Fruit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PoolID != other.PoolID) return false;
      if (PropID != other.PropID) return false;
      if(!propRange_.Equals(other.propRange_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PoolID != 0) hash ^= PoolID.GetHashCode();
      if (PropID != 0) hash ^= PropID.GetHashCode();
      hash ^= propRange_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PoolID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PoolID);
      }
      if (PropID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PropID);
      }
      propRange_.WriteTo(output, _repeated_propRange_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PoolID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PoolID);
      }
      if (PropID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PropID);
      }
      propRange_.WriteTo(ref output, _repeated_propRange_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PoolID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PoolID);
      }
      if (PropID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PropID);
      }
      size += propRange_.CalculateSize(_repeated_propRange_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Fruit other) {
      if (other == null) {
        return;
      }
      if (other.PoolID != 0) {
        PoolID = other.PoolID;
      }
      if (other.PropID != 0) {
        PropID = other.PropID;
      }
      propRange_.Add(other.propRange_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PoolID = input.ReadInt32();
            break;
          }
          case 16: {
            PropID = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            propRange_.AddEntriesFrom(input, _repeated_propRange_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PoolID = input.ReadInt32();
            break;
          }
          case 16: {
            PropID = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            propRange_.AddEntriesFrom(ref input, _repeated_propRange_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
