// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/Spec/Goods.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lumber.Spec {

  /// <summary>Holder for reflection information generated from proto/Spec/Goods.proto</summary>
  public static partial class GoodsReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/Spec/Goods.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GoodsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZwcm90by9TcGVjL0dvb2RzLnByb3RvEgtsdW1iZXIuU3BlYyKgAQoFR29v",
            "ZHMSEAoIR29vZHNfSUQYASABKAUSEgoKR29vZHNfVHlwZRgCIAEoBRISCgpH",
            "b29kc19OYW1lGAMgASgJEhAKCFBheV9Qcm9wGAQgASgFEg0KBVByaWNlGAUg",
            "ASgFEhUKDUluY2x1ZGVfZ29vZHMYBiADKAUSEQoJR29vZHNfTnVtGAcgAygF",
            "EhIKCkdvb2RzX0ljb24YCCABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lumber.Spec.Goods), global::Lumber.Spec.Goods.Parser, new[]{ "GoodsID", "GoodsType", "GoodsName", "PayProp", "Price", "IncludeGoods", "GoodsNum", "GoodsIcon" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Goods : pb::IMessage<Goods>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Goods> _parser = new pb::MessageParser<Goods>(() => new Goods());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Goods> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lumber.Spec.GoodsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Goods() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Goods(Goods other) : this() {
      goodsID_ = other.goodsID_;
      goodsType_ = other.goodsType_;
      goodsName_ = other.goodsName_;
      payProp_ = other.payProp_;
      price_ = other.price_;
      includeGoods_ = other.includeGoods_.Clone();
      goodsNum_ = other.goodsNum_.Clone();
      goodsIcon_ = other.goodsIcon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Goods Clone() {
      return new Goods(this);
    }

    /// <summary>Field number for the "Goods_ID" field.</summary>
    public const int GoodsIDFieldNumber = 1;
    private int goodsID_;
    /// <summary>
    /// 商品ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GoodsID {
      get { return goodsID_; }
      set {
        goodsID_ = value;
      }
    }

    /// <summary>Field number for the "Goods_Type" field.</summary>
    public const int GoodsTypeFieldNumber = 2;
    private int goodsType_;
    /// <summary>
    /// 商品分类
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GoodsType {
      get { return goodsType_; }
      set {
        goodsType_ = value;
      }
    }

    /// <summary>Field number for the "Goods_Name" field.</summary>
    public const int GoodsNameFieldNumber = 3;
    private string goodsName_ = "";
    /// <summary>
    /// 商品名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GoodsName {
      get { return goodsName_; }
      set {
        goodsName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Pay_Prop" field.</summary>
    public const int PayPropFieldNumber = 4;
    private int payProp_;
    /// <summary>
    /// 支付道具
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PayProp {
      get { return payProp_; }
      set {
        payProp_ = value;
      }
    }

    /// <summary>Field number for the "Price" field.</summary>
    public const int PriceFieldNumber = 5;
    private int price_;
    /// <summary>
    /// 价格
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "Include_goods" field.</summary>
    public const int IncludeGoodsFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_includeGoods_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> includeGoods_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 包含道具
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> IncludeGoods {
      get { return includeGoods_; }
    }

    /// <summary>Field number for the "Goods_Num" field.</summary>
    public const int GoodsNumFieldNumber = 7;
    private static readonly pb::FieldCodec<int> _repeated_goodsNum_codec
        = pb::FieldCodec.ForInt32(58);
    private readonly pbc::RepeatedField<int> goodsNum_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 道具数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> GoodsNum {
      get { return goodsNum_; }
    }

    /// <summary>Field number for the "Goods_Icon" field.</summary>
    public const int GoodsIconFieldNumber = 8;
    private string goodsIcon_ = "";
    /// <summary>
    /// 商品Icon
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GoodsIcon {
      get { return goodsIcon_; }
      set {
        goodsIcon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Goods);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Goods other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GoodsID != other.GoodsID) return false;
      if (GoodsType != other.GoodsType) return false;
      if (GoodsName != other.GoodsName) return false;
      if (PayProp != other.PayProp) return false;
      if (Price != other.Price) return false;
      if(!includeGoods_.Equals(other.includeGoods_)) return false;
      if(!goodsNum_.Equals(other.goodsNum_)) return false;
      if (GoodsIcon != other.GoodsIcon) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GoodsID != 0) hash ^= GoodsID.GetHashCode();
      if (GoodsType != 0) hash ^= GoodsType.GetHashCode();
      if (GoodsName.Length != 0) hash ^= GoodsName.GetHashCode();
      if (PayProp != 0) hash ^= PayProp.GetHashCode();
      if (Price != 0) hash ^= Price.GetHashCode();
      hash ^= includeGoods_.GetHashCode();
      hash ^= goodsNum_.GetHashCode();
      if (GoodsIcon.Length != 0) hash ^= GoodsIcon.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GoodsID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GoodsID);
      }
      if (GoodsType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodsType);
      }
      if (GoodsName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GoodsName);
      }
      if (PayProp != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PayProp);
      }
      if (Price != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Price);
      }
      includeGoods_.WriteTo(output, _repeated_includeGoods_codec);
      goodsNum_.WriteTo(output, _repeated_goodsNum_codec);
      if (GoodsIcon.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(GoodsIcon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GoodsID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GoodsID);
      }
      if (GoodsType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodsType);
      }
      if (GoodsName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GoodsName);
      }
      if (PayProp != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PayProp);
      }
      if (Price != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Price);
      }
      includeGoods_.WriteTo(ref output, _repeated_includeGoods_codec);
      goodsNum_.WriteTo(ref output, _repeated_goodsNum_codec);
      if (GoodsIcon.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(GoodsIcon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GoodsID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsID);
      }
      if (GoodsType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsType);
      }
      if (GoodsName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GoodsName);
      }
      if (PayProp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PayProp);
      }
      if (Price != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
      }
      size += includeGoods_.CalculateSize(_repeated_includeGoods_codec);
      size += goodsNum_.CalculateSize(_repeated_goodsNum_codec);
      if (GoodsIcon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GoodsIcon);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Goods other) {
      if (other == null) {
        return;
      }
      if (other.GoodsID != 0) {
        GoodsID = other.GoodsID;
      }
      if (other.GoodsType != 0) {
        GoodsType = other.GoodsType;
      }
      if (other.GoodsName.Length != 0) {
        GoodsName = other.GoodsName;
      }
      if (other.PayProp != 0) {
        PayProp = other.PayProp;
      }
      if (other.Price != 0) {
        Price = other.Price;
      }
      includeGoods_.Add(other.includeGoods_);
      goodsNum_.Add(other.goodsNum_);
      if (other.GoodsIcon.Length != 0) {
        GoodsIcon = other.GoodsIcon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GoodsID = input.ReadInt32();
            break;
          }
          case 16: {
            GoodsType = input.ReadInt32();
            break;
          }
          case 26: {
            GoodsName = input.ReadString();
            break;
          }
          case 32: {
            PayProp = input.ReadInt32();
            break;
          }
          case 40: {
            Price = input.ReadInt32();
            break;
          }
          case 50:
          case 48: {
            includeGoods_.AddEntriesFrom(input, _repeated_includeGoods_codec);
            break;
          }
          case 58:
          case 56: {
            goodsNum_.AddEntriesFrom(input, _repeated_goodsNum_codec);
            break;
          }
          case 66: {
            GoodsIcon = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GoodsID = input.ReadInt32();
            break;
          }
          case 16: {
            GoodsType = input.ReadInt32();
            break;
          }
          case 26: {
            GoodsName = input.ReadString();
            break;
          }
          case 32: {
            PayProp = input.ReadInt32();
            break;
          }
          case 40: {
            Price = input.ReadInt32();
            break;
          }
          case 50:
          case 48: {
            includeGoods_.AddEntriesFrom(ref input, _repeated_includeGoods_codec);
            break;
          }
          case 58:
          case 56: {
            goodsNum_.AddEntriesFrom(ref input, _repeated_goodsNum_codec);
            break;
          }
          case 66: {
            GoodsIcon = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
