// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/DataTable/UserData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lumber.DataTable {

  /// <summary>Holder for reflection information generated from proto/DataTable/UserData.proto</summary>
  public static partial class UserDataReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/DataTable/UserData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5wcm90by9EYXRhVGFibGUvVXNlckRhdGEucHJvdG8SEGx1bWJlci5EYXRh",
            "VGFibGUaHXByb3RvL0RhdGFUYWJsZS9Vc2VyQXhlLnByb3RvGh5wcm90by9E",
            "YXRhVGFibGUvVXNlclRyZWUucHJvdG8ieQoIVXNlckRhdGESKAoEdHJlZRgB",
            "IAEoCzIaLmx1bWJlci5EYXRhVGFibGUuVXNlclRyZWUSJwoEYXhlcxgCIAMo",
            "CzIZLmx1bWJlci5EYXRhVGFibGUuVXNlckF4ZRIMCgRjb2luGAMgASgFEgwK",
            "BHJvc2UYBCABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Lumber.DataTable.UserAxeReflection.Descriptor, global::Lumber.DataTable.UserTreeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lumber.DataTable.UserData), global::Lumber.DataTable.UserData.Parser, new[]{ "Tree", "Axes", "Coin", "Rose" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 玩家数据
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UserData : pb::IMessage<UserData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserData> _parser = new pb::MessageParser<UserData>(() => new UserData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lumber.DataTable.UserDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserData(UserData other) : this() {
      tree_ = other.tree_ != null ? other.tree_.Clone() : null;
      axes_ = other.axes_.Clone();
      coin_ = other.coin_;
      rose_ = other.rose_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserData Clone() {
      return new UserData(this);
    }

    /// <summary>Field number for the "tree" field.</summary>
    public const int TreeFieldNumber = 1;
    private global::Lumber.DataTable.UserTree tree_;
    /// <summary>
    /// 仙树数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lumber.DataTable.UserTree Tree {
      get { return tree_; }
      set {
        tree_ = value;
      }
    }

    /// <summary>Field number for the "axes" field.</summary>
    public const int AxesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Lumber.DataTable.UserAxe> _repeated_axes_codec
        = pb::FieldCodec.ForMessage(18, global::Lumber.DataTable.UserAxe.Parser);
    private readonly pbc::RepeatedField<global::Lumber.DataTable.UserAxe> axes_ = new pbc::RepeatedField<global::Lumber.DataTable.UserAxe>();
    /// <summary>
    ///斧子数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Lumber.DataTable.UserAxe> Axes {
      get { return axes_; }
    }

    /// <summary>Field number for the "coin" field.</summary>
    public const int CoinFieldNumber = 3;
    private int coin_;
    /// <summary>
    /// 金币
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Coin {
      get { return coin_; }
      set {
        coin_ = value;
      }
    }

    /// <summary>Field number for the "rose" field.</summary>
    public const int RoseFieldNumber = 4;
    private int rose_;
    /// <summary>
    /// 玫瑰
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rose {
      get { return rose_; }
      set {
        rose_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Tree, other.Tree)) return false;
      if(!axes_.Equals(other.axes_)) return false;
      if (Coin != other.Coin) return false;
      if (Rose != other.Rose) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (tree_ != null) hash ^= Tree.GetHashCode();
      hash ^= axes_.GetHashCode();
      if (Coin != 0) hash ^= Coin.GetHashCode();
      if (Rose != 0) hash ^= Rose.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (tree_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Tree);
      }
      axes_.WriteTo(output, _repeated_axes_codec);
      if (Coin != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Coin);
      }
      if (Rose != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Rose);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (tree_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Tree);
      }
      axes_.WriteTo(ref output, _repeated_axes_codec);
      if (Coin != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Coin);
      }
      if (Rose != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Rose);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (tree_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Tree);
      }
      size += axes_.CalculateSize(_repeated_axes_codec);
      if (Coin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Coin);
      }
      if (Rose != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rose);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserData other) {
      if (other == null) {
        return;
      }
      if (other.tree_ != null) {
        if (tree_ == null) {
          Tree = new global::Lumber.DataTable.UserTree();
        }
        Tree.MergeFrom(other.Tree);
      }
      axes_.Add(other.axes_);
      if (other.Coin != 0) {
        Coin = other.Coin;
      }
      if (other.Rose != 0) {
        Rose = other.Rose;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (tree_ == null) {
              Tree = new global::Lumber.DataTable.UserTree();
            }
            input.ReadMessage(Tree);
            break;
          }
          case 18: {
            axes_.AddEntriesFrom(input, _repeated_axes_codec);
            break;
          }
          case 24: {
            Coin = input.ReadInt32();
            break;
          }
          case 32: {
            Rose = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (tree_ == null) {
              Tree = new global::Lumber.DataTable.UserTree();
            }
            input.ReadMessage(Tree);
            break;
          }
          case 18: {
            axes_.AddEntriesFrom(ref input, _repeated_axes_codec);
            break;
          }
          case 24: {
            Coin = input.ReadInt32();
            break;
          }
          case 32: {
            Rose = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
