#!/bin/sh

fs_alert_url='https://open.feishu.cn/open-apis/bot/v2/hook/fae1ba9c-36ed-4f84-b413-abba02c3b31f'

cd "$(dirname "$0")/../.." || exit 1

excel_dir=./specs/excel
if [ ! -d ${excel_dir} ]; then
  echo "dir ${excel_dir} not exist yet!"
  exit 0
fi

excel_md5_file=./scripts/hooks/excel_md5.txt
if [ ! -f ${excel_md5_file} ]; then
  touch ${excel_md5_file}
fi

cur_md5=$(find ${excel_dir} -type f -exec md5 {} \;)
last_md5=$(cat ${excel_md5_file})

if [ "${cur_md5}" != "${last_md5}" ]; then
  echo "${cur_md5}" > ${excel_md5_file}
  sh ./scripts/generate.sh
  git add .
  curl -X POST -H "Content-Type: application/json;charset=utf-8" \
      -d '{"msg_type":"interactive","card":{"config":{"wide_screen_mode":true}, "elements":[{"tag":"div", "text":{"content":"配置表下载地址:https://gitlab.17zhuyu.com/zhengyong/lumber_proto/tree/master/specs/output", "tag":"lark_md"}}], "header":{"title":{"content":"配置表已更新", "tag":"plain_text"}, "template":"turquoise"}}}' \
      ${fs_alert_url}
fi

exit 0